app:
  name: techwave-app
  namespace: techwave
  image:
    repository: javrip/techwave-app
    tag: d5b5d23
  replicas: 2
  port: 5000
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  activeVersion: blue