{{- if eq .Values.version "blue" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.app.name }}-policy
  namespace: {{ .Values.app.namespace }}
spec:
  podSelector: {}    # A qué pods aplica (vacío = todos)
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx			  
      ports:
        - port: {{ .Values.app.port }}
{{- end }}