{{- if eq .Values.version "blue" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  # Valores en base64. Para codificar: echo -n "valor" | base64
  SECRET_KEY: dGVjaHdhdmUtc2VjcmV0LWtleQ==   # "techwave-secret-key"
  APP_TOKEN: dGVjaHdhdmUtdG9rZW4=             # "techwave-token"
{{- end }}